controller_frequency: 2     # run controller at 5.0 Hz. This value defines how fast the MiR is getting. Because the time of one cycle times the acceleration is the max valocity the MiR is reaching
controller_patience: 15.0    # if the controller failed, clear obstacles and retry; after 15.0 s, abort and replan
planner_frequency: 0.0       # don't continually replan (only when controller failed)
planner_patience: 5.0        # if the first planning attempt failed, abort planning retries after 5.0 s...
max_planning_retries: 10     # ... or after 10 attempts (whichever happens first)
oscillation_timeout: 30.0    # abort controller and trigger recovery behaviors after 30.0 s

# These frame definitions are used in the MoveBaseAction from move_base_flex to define the global coordinate system and the locate coodinate system where the robot currently is
global_frame: map # default: map
robot_frame: $(arg tf_prefix_slashed)base_link # $(arg tf_prefix) default: base_link without the tf_prefix. This is necessary when we want to use multiple robots!
