position_joint_controller:
  type: position_controllers/JointTrajectoryController
  joints: *robot_joints
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
