<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
	<xacro:include filename="$(find mir_description)/urdf/mir_600/mir_600_wheels.gazebo.xacro" />
	<xacro:include filename="$(find mir_description)/urdf/general/sick_s300.gazebo.xacro" />
	<xacro:include filename="$(find mir_description)/urdf/general/imu.gazebo.xacro" />
	<xacro:include filename="$(find mir_description)/urdf/general/plugins.gazebo.xacro" />
	<xacro:include filename="$(find mir_description)/urdf/general/_d435.gazebo.xacro" />

	<xacro:property name="imu_standard_deviation" value="0.00017" />

	<xacro:macro name="mir_600_gazebo" params="tf_prefix robot_namespace">

		<!-- Predefine some values that are necessary later. It is important to differenciate between empty and not empty robot_namespace and tf_prefix -->
		<xacro:if value="${robot_namespace == ''}">
			<xacro:property name="robot_namespace_slashed" value="/" />
		</xacro:if>
		<xacro:unless value="${robot_namespace == ''}">
				<xacro:property name="robot_namespace_slashed" value="${robot_namespace}/" />
		</xacro:unless>

		<xacro:if value="${tf_prefix == ''}">
			<xacro:property name="tf_prefix_slashed" value="" />
		</xacro:if>
		<xacro:unless value="${tf_prefix == ''}">
				<xacro:property name="tf_prefix_slashed" value="${tf_prefix}/" />
		</xacro:unless>

		<xacro:if value="${robot_namespace == ''}">
			<xacro:property name="robot_namespace_underscored" value="" />
		</xacro:if>
		<xacro:unless value="${robot_namespace == ''}">
				<xacro:property name="robot_namespace_underscored" value="${robot_namespace}_" />
		</xacro:unless>

		<!-- Set Gazebo material for the base -->
		<gazebo reference="base_link">
			<material>Gazebo/Grey</material>
		</gazebo>

		<!-- Set gazebo material for the wheels -->
		<xacro:actuated_wheel_gazebo locationprefix="left"/>
		<xacro:actuated_wheel_gazebo locationprefix="right"/>
		<xacro:caster_wheel_gazebo locationprefix="fl"/>
		<xacro:caster_wheel_gazebo locationprefix="fr"/>
		<xacro:caster_wheel_gazebo locationprefix="bl"/>
		<xacro:caster_wheel_gazebo locationprefix="br"/>

		<!-- Add transmissions to wheels -->
		<xacro:mir_600_wheel_transmissions/>

		<!-- Settings for the IMU of the robot to work in the simulation environment-->
		<xacro:imu_gazebo link="imu_link" robot_namespace="${robot_namespace_slashed}" imu_topic="imu_data" update_rate="50.0" standard_deviation="${imu_standard_deviation}" />

		<!-- Add Gazebo xacro for the laser scanner to work in Gazebo -->
		<!-- Please match there macro calls with the sick_s300 xacro calls in the mir_600.urdf.xacro file-->
		<xacro:sick_s300_gazebo link="front_laser_link" robot_namespace="${robot_namespace_slashed}" topic="f_scan" tf_prefix="${tf_prefix_slashed}"/>
		<xacro:sick_s300_gazebo link="back_laser_link" robot_namespace="${robot_namespace_slashed}" topic="b_scan" tf_prefix="${tf_prefix_slashed}"/>

		<!-- Settings for the camera of the robot to work in the simulation environment-->
    	<xacro:gazebo_d435 camera_name="${robot_namespace_underscored}camera" reference_link="camera_link" topics_ns="${robot_namespace_slashed}camera" depth_optical_frame="${tf_prefix_slashed}camera_depth_optical_frame" color_optical_frame="${tf_prefix_slashed}camera_color_optical_frame" infrared1_optical_frame="${tf_prefix_slashed}camera_left_ir_optical_frame" infrared2_optical_frame="${tf_prefix_slashed}camera_right_ir_optical_frame" publish_pointcloud="true"/>


		<!-- disabled, because it doesn't make a difference in Gazebo: -->
		<!-- <xacro:set_all_wheel_frictions tf_prefix="${tf_prefix}"/> -->

		<!-- This part of the file looks like it is not necessary for the correct function of the urdf files.-->
		<!-- Remove this part in a second iteration when all functions are working like they are supposed to be-->

		<!-- <xacro:macro name="diff_controller_plugin_gazebo" params="prefix left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
			<gazebo>
			<plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<legacyMode>false</legacyMode>
				<alwaysOn>true</alwaysOn>
				<updateRate>1000.0</updateRate>
				<leftJoint>${left_wheel_joint}</leftJoint>
				<rightJoint>${right_wheel_joint}</rightJoint>
				<wheelSeparation>${wheel_separation}</wheelSeparation>
				<wheelDiameter>${2*wheel_radius}</wheelDiameter>
				<wheelTorque>10</wheelTorque>
				<publishTf>1</publishTf>
				<odometryFrame>map</odometryFrame>
				<commandTopic>mobile_base_controller/cmd_vel</commandTopic>
				<odometryTopic>mobile_base_controller/odom</odometryTopic>
				<robotBaseFrame>base_footprint</robotBaseFrame>
				<wheelAcceleration>2.8</wheelAcceleration>
				<publishWheelJointState>true</publishWheelJointState>
				<publishWheelTF>false</publishWheelTF>
				<odometrySource>world</odometrySource>
				<rosDebugLevel>Debug</rosDebugLevel>
			</plugin>
			</gazebo>
		</xacro:macro> -->

		<!-- <xacro:macro name="set_wheel_friction" params="link friction">
			<gazebo reference="${link}">
			<mu1 value="${friction}"/>
			<mu2 value="${friction}"/>
			<kp value="10000000.0"/>
			<kd value="1.0"/>
			</gazebo>
		</xacro:macro>

		<xacro:macro name="set_all_wheel_frictions" params="prefix">
			<xacro:set_wheel_friction link="${prefix}left_wheel_link" friction="200"/>
			<xacro:set_wheel_friction link="${prefix}right_wheel_link" friction="200"/>
			<xacro:set_wheel_friction link="${prefix}fl_caster_wheel_link" friction="1"/>
			<xacro:set_wheel_friction link="${prefix}fr_caster_wheel_link" friction="1"/>
			<xacro:set_wheel_friction link="${prefix}bl_caster_wheel_link" friction="1"/>
			<xacro:set_wheel_friction link="${prefix}br_caster_wheel_link" friction="1"/>
		</xacro:macro> -->

		<!-- <p3d_base_controller tf_prefix="${tf_prefix}" /> -->

		<!-- Settings for the camera of the robot to work in the simulation environment-->
		<!--gazebo reference="camera_link">  
			<sensor type="depth" name="camera">
			<plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
				<cameraName>camera</cameraName>
				<alwaysOn>true</alwaysOn>
				<updateRate>10</updateRate>
				<imageTopicName>rgb/image_raw</imageTopicName>
				<depthImageTopicName>depth/image_raw</depthImageTopicName>
				<pointCloudTopicName>depth/points</pointCloudTopicName>
				<cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
				<depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
				<frameName>camera_link_optical</frameName>
				<baseline>0.1</baseline>
				<distortion_k1>0.0</distortion_k1>
				<distortion_k2>0.0</distortion_k2>
				<distortion_k3>0.0</distortion_k3>
				<distortion_t1>0.0</distortion_t1>
				<distortion_t2>0.0</distortion_t2>
				<pointCloudCutoff>0.4</pointCloudCutoff>
			</plugin>
			</sensor>
		</gazebo-->
	</xacro:macro>
</robot>
