compliant_axis_controller:
  type: "ur_controllers_extended/CompliantAxisController"
  joints: *robot_joints
  d_gain: 5
  joint_stiffness: 5 #Nm/rad
  topic_name: wrench
  direction: z

compliant_axis_vel_controller:
  type: "ur_controllers_extended/CompliantAxisVelController"
  joints: *robot_joints
  p_gain: 1.4
  d_gain: 0.3
  theta: 0.0
  joint_stiffness: 5 #Nm/rad
  topic_name: wrench
  direction: z
