$(arg arm_id)_arm: &arm_config
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05

$(arg arm_id)_manipulator: *arm_config
