GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.01
  visualize_potential: true # false
  use_dijkstra: true  #1#true #If true, use dijkstra's algorithm. Otherwise, A*. 
  use_quadratic: true  #2#true #If true, use the quadratic approximation of the ##potential##. Otherwise, use a simpler calculation. 
  use_grid_path: false  #3#false #If true, create a path that follows the grid boundaries. Otherwise, use a gradient descent method. 
  old_navfn_behavior: false #4#false #If for some reason, you want global_planner to exactly mirror the behavior of navfn, set this to true
  lethal_cost: 253
  neutral_cost: 66 #50
  cost_factor: 0.55 #3.0
  publish_potential: true
  orientation_mode: 1           #Place Orientation parallel to path
  orientation_window_size: 1.0