controller_list:
  - name: $(arg prefix)_l/arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - $(arg prefix)_l/shoulder_pan_joint
      - $(arg prefix)_l/shoulder_lift_joint
      - $(arg prefix)_l/elbow_joint
      - $(arg prefix)_l/wrist_1_joint
      - $(arg prefix)_l/wrist_2_joint
      - $(arg prefix)_l/wrist_3_joint

  - name: $(arg prefix)_r/arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - $(arg prefix)_r/shoulder_pan_joint
      - $(arg prefix)_r/shoulder_lift_joint
      - $(arg prefix)_r/elbow_joint
      - $(arg prefix)_r/wrist_1_joint
      - $(arg prefix)_r/wrist_2_joint
      - $(arg prefix)_r/wrist_3_joint

  - name: $(arg prefix)_l/lift_controller 
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - left_lift_joint

  - name: $(arg prefix)_r/lift_controller 
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - right_lift_joint